services:
  server:
    build: ./server
    command: python src/starter.py --host=server --port=12345 --db-name=server_db --db-user-name=server_user --db-user-password=server_password --db-host=db --db-port=3306
    ports:
      - '12345:12345'
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '33306:3306'
    environment:
      MYSQL_DATABASE: 'server_db'
      MYSQL_USER: 'server_user'
      MYSQL_PASSWORD: 'server_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    restart: always