services:
  server:
    build: ./server
    command: python src/starter.py
    ports:
      - '12345:12345'
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '33306:3306'
    environment:
      MYSQL_DATABASE: 'server_db'
      MYSQL_USER: 'server_user'
      MYSQL_PASSWORD: 'server_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    restart: always